# Generated by Django 5.0.2 on 2024-02-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_mvp_name_remove_mvp_team_remove_mvp_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvp',
            name='Rank',
            field=models.CharField(default='Rank', max_length=10),
        ),
    ]
