# Generated by Django 5.0.2 on 2024-02-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_mvp_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvp',
            name='First',
            field=models.FloatField(default=0.0),
        ),
    ]
