# Generated by Django 5.0.2 on 2024-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_mvp_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvp',
            name='Age',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mvp',
            name='G',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mvp',
            name='Pts_Max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mvp',
            name='Pts_Won',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mvp',
            name='Year',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Age',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='G',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='GS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Rk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Year',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='W',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='Year',
            field=models.FloatField(default=0.0),
        ),
    ]
